from enum import StrEnum


class AccountType(StrEnum):
    ACTIVO = "ACTIVO"
    PASIVO = "PASIVO"
    PATRIMONIO = "PATRIMONIO"
    INGRESO = "INGRESO"
    COSTO = "COSTO"
    GASTO = "GASTO"
    OTRO = "OTRO"


class AccountNature(StrEnum):
    DEUDORA = "DEUDORA"
    ACREEDORA = "ACREEDORA"
    OTRA = "OTRA"


class FinancialStatement(StrEnum):
    BALANCE_COMPROBACION = "BALANCE_COMPROBACION"
    ESTADO_SITUACION_FINANCIERA = "ESTADO_SITUACION_FINANCIERA"
    ESTADO_RESULTADOS = "ESTADO_RESULTADOS"
    FLUJO_EFECTIVO = "FLUJO_EFECTIVO"
    DESCONOCIDO = "DESCONOCIDO"


class MatchType(StrEnum):
    EXACT_CODE = "EXACT_CODE"
    CODE_AND_NAME = "CODE_AND_NAME"
    NORMALIZED_NAME = "NORMALIZED_NAME"
    ALIAS = "ALIAS"
    CONTEXT = "CONTEXT"
    FUZZY = "FUZZY"
    NONE = "NONE"


class RowStatus(StrEnum):
    MATCHED = "MATCHED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    UNKNOWN = "UNKNOWN"
    NEW_ACCOUNT = "NEW_ACCOUNT"
    ERROR = "ERROR"
    IGNORED = "IGNORED"


class RowClassification(StrEnum):
    CUENTA = "CUENTA"
    SUBTOTAL = "SUBTOTAL"
    TOTAL = "TOTAL"
    ENCABEZADO = "ENCABEZADO"
    NOTA = "NOTA"
    IGNORAR = "IGNORAR"


class ImportStatus(StrEnum):
    UPLOADED = "UPLOADED"
    ANALYZING = "ANALYZING"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    APPROVED = "APPROVED"
    IMPORTED = "IMPORTED"
    FAILED = "FAILED"
